# Generated by Django 5.1.1 on 2024-09-21 14:44

import django.db.models.deletion
import image.image_path.product_img_path
import image.validators.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Enter the name of the category (e.g., 'Electronics').",
                        max_length=250,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique slug identifier for this category (e.g., 'electronics').",
                        max_length=250,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the product (e.g., 'Smartphone').",
                        max_length=250,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        default="un-branded",
                        help_text="Enter the brand name of the product (e.g., 'Apple').",
                        max_length=250,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Enter a description for the product (optional).",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique slug identifier for this product (e.g., 'smartphone').",
                        max_length=250,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter the price of the product (e.g., 99.99).",
                        max_digits=4,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a product image (Allowed formats: jpg, jpeg, png, gif, webp, png)",
                        null=True,
                        upload_to=image.image_path.product_img_path.product_image_upload_path,
                        validators=[
                            image.validators.image_validators.validate_image_file_extension,
                            image.validators.image_validators.resize_and_fit_image,
                        ],
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The category to which this product belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="store.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "products",
            },
        ),
    ]
